---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: optimizely-decision-service-grpc
  labels:
    app: optimizely-decision-service-grpc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: optimizely-decision-service-grpc
  template:
    metadata:
      labels:
        app: optimizely-decision-service-grpc 
    spec:
      containers:
      - name: optimizely-decision-service-grpc 
        image: 489198589229.dkr.ecr.eu-west-1.amazonaws.com/optimizely-hackathon:latest
        env:
          - name: DEPLOYMENT_NAME
            value: dev
          - name: OPTIMIZELY_SDK_KEY
            value: BqkQa68GRXuKdvUt5qu7pU
        ports:
        - containerPort: 50051
                

---
apiVersion: v1
kind: Service
metadata:
  name: optimizely-decision-service-grpc-service 
spec:
  selector:
    app: optimizely-decision-service-grpc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 50051
