# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import activate_pb2 as internal_dot_activate_dot_activate__pb2


class ActivateStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Activate = channel.unary_unary(
                '/activate.Activate/Activate',
                request_serializer=internal_dot_activate_dot_activate__pb2.ActivateRequest.SerializeToString,
                response_deserializer=internal_dot_activate_dot_activate__pb2.ActivateResponse.FromString,
                )


class ActivateServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Activate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ActivateServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Activate': grpc.unary_unary_rpc_method_handler(
                    servicer.Activate,
                    request_deserializer=internal_dot_activate_dot_activate__pb2.ActivateRequest.FromString,
                    response_serializer=internal_dot_activate_dot_activate__pb2.ActivateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'activate.Activate', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Activate(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Activate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/activate.Activate/Activate',
            internal_dot_activate_dot_activate__pb2.ActivateRequest.SerializeToString,
            internal_dot_activate_dot_activate__pb2.ActivateResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
